theme: minima
title: Shan Kothari
description: Assistant Professor, University of Alberta (he/il)
email: shan.kothari@ualberta.ca
url: "http://shankothari.github.io"
twitter_username: ShanKothari
github_username: ShanKothari
markdown: kramdown
