theme: jekyll-theme-minimal
title: Shan Kothari
description: PhD Candidate, Plant Biology, University of Minnesota
email: kotha020@umn.edu
url: "http://shankothari.github.io"
twitter_username: ShanKothari
github_username: ShanKothari
