theme: minima
title: Shan Kothari
description: Postdoctoral researcher, Université de Montréal (he/him)
email: shan.kothari@umontreal.ca
url: "http://shankothari.github.io"
twitter_username: ShanKothari
github_username: ShanKothari
markdown: kramdown
